article/urls.py
from django.urls import path
from . import views

app_name = 'article'

urlpatterns = [
    path('', views.article, name='article'),
    path('article-1/', views.artikelsatu, name='artikelsatu'),
    path('article-2/', views.artikeldua, name='artikeldua'),
]

catering/urls.py
from django.contrib import admin
from django.urls import path, include

urlpatterns = [
    path('admin/', admin.site.urls),
    path('', include('homepage.urls')),
    path('order/', include('order.urls')),
    path('article/', include('article.urls')),
]

homepage/urls.py
from django.urls import path
from . import views

app_name = 'homepage'

urlpatterns = [
    path('', views.homepage, name='homepage'),
    path('qna/', views.qna, name='qna'),
    path('about-us/', views.about_us, name='about-us'),
    path('our-team/', views.our_team, name='our-team'),
    # dilanjutkan ...
]

order/urls.py
from django.urls import path
from . import views

app_name = 'order'

urlpatterns = [
    path('', views.form_order, name = 'form_order')
]

article/models.py
from django.db import models

# Create your models here.
class Key(models.Model):
    title = models.CharField(max_length=200)
    urls = models.CharField(max_length=100)
    ##answer = models.CharField(max_length=10000000)

    def __str__(self):
        return self.title

homepage/models.py
from django.db import models

# Create your models here.
class Answer(models.Model):
    key = models.CharField(max_length=50)
    answer = models.CharField(max_length=200)

    def __str__(self):
        return self.key

menu/models.py
from django.db import models

# Create your models here.

order/models.py
from django.db import models

# Create your models here.

class FormPemesanan(models.Model):
	namaPemesan = models.CharField(max_length = 50)
	pilihanMenu = models.CharField(max_length = 500)
	alamatPengiriman = models.CharField(max_length = 80)
	jenisPembayaran = models.CharField(max_length = 30)
	nomorTelepon = models.IntegerField(default=0)
	notes = models.TextField()

	def __str__(self):
		return self.namaPemesan

article/views.py
from django.shortcuts import render

# Create your views here.
def article(request):
    return render(request, 'katering_article.html')

def artikelsatu(request):
    return render(request, 'article_one.html')  

def artikeldua(request):
    return render(request, 'article_two.html')    

def search(request):
    query = request.GET.get()
    if query:
        # query example
        results = Key.objects.filter(name__contains=query)
    else:
        results = []
    return render(request, katering_article.html, {'results': results})

homepage/views.py
from django.shortcuts import render
from .models import Answer

# Create your views here.
def homepage(request):
    return render(request, 'Homepage.html')

def about_us(request):
    return render(request, 'About Us.html')

def our_team(request):
    return render(request, 'OurTeam-page.html')

def qna(request):
    if request.method == 'POST':
        splitted_keyword = request.POST.get('keyword').split(" ")
        answer = Answer.objects.all().get(key="notfound")
        for word in splitted_keyword:
            if len(Answer.objects.filter(key=word.lower()))==1:
                answer = Answer.objects.all().get(key=word)
        return render(request, 'QnA-page.html', {'answer' : answer})
    else:
        return render(request, 'QnA-page.html')

menu/views.py
from django.shortcuts import render

# Create your views here.

order/views.py
from django.shortcuts import render
from .models import FormPemesanan

# Create your views here.
def form_order(request):

	if request.method == 'POST':

		nama_pemesan = request.POST.get('nama')
		pilihan_menu = request.POST.get('menu')
		alamat = request.POST.get('alamat')
		pembayaran = request.POST.get('pembayaran')
		no_telp = request.POST.get('telepon')
		notes = request.POST.get('notes')

		form_pemesanan = FormPemesanan(namaPemesan = nama_pemesan, pilihanMenu = pilihan_menu, alamatPengiriman = alamat, jenisPembayaran = pembayaran, nomorTelepon = no_telp, notes = notes)
		form_pemesanan.save()

		ucapan_terima_kasih = 'Terima kasih telah mengisi form ini ya!'
		terimakasih = [ucapan_terima_kasih]

		return render(request, 'Form Pemesanan.html', {'terimakasih' : ''})

	else:
		return render(request, 'Form Pemesanan.html')

article/templates/article_one.html
<!DOCTYPE html>
{% load static %}
<html lang="en">
<head>
  <title>Diet Keto Bisa Picu Peradangan Kulit, Apa Sebabnya?</title>
  <meta charset="utf-8">
  <meta name="viewport" content="width=device-width, initial-scale=1">
  <link rel="stylesheet" href="https://maxcdn.bootstrapcdn.com/bootstrap/3.4.0/css/bootstrap.min.css">
  <script src="https://ajax.googleapis.com/ajax/libs/jquery/3.4.1/jquery.min.js"></script>
  <script src="https://maxcdn.bootstrapcdn.com/bootstrap/3.4.0/js/bootstrap.min.js"></script>

  <link rel="stylesheet" type="text/css" href="{% static 'css/article.css' %}">

  <link href='https://fonts.googleapis.com/css?family=Montserrat' rel='stylesheet'>

</head>


<body class="articlebg">
  <div class="container-fluid">
    <div class="row">
      <div class="col-sm-1"> </div>
      <div class="col-sm-8">
         <a href="{% url 'article:article' %}" class="btn btn-info" role="button"> << Back to Article </a>
      </div>
      <div class="col-sm-3"> </div>
    </div></div>

  <br><br>
	<div class="container-fluid">
			<br><br>
          <div class="row">
            <div class="col-sm-1"><br></div>
            
            <div class="col-sm-10">
              <p class="x">Diet Keto Bisa Picu Peradangan Kulit, Apa Sebabnya?</p>
              <hr class="new5" style="border: 2px solid black;">
              <p class="lildesc">Written by Nabilla Tashandra - Kompas. Date released 19 Oktober 2019</p>
              <br>
              <img class="featuredarticle" src="{% static 'images/f.jpg' %}" alt="New York" style="height:70%; width:70%;">
              <br>
              <p class="descarticle">KOMPAS.com - Kita semua tahu bahwa pola makan punya dampak yang berbeda-beda pada setiap individu. Pola makan juga sangat berdampak pada kulit. Banyak mengonsumsi makanan olahan dan tinggi gula, misalnya, terbukti merusak kulit. Sementara, banyak mengonsumsi sumber makanan nabati bisa membuat kulit tampak lebih berkilau dan halus. Sebuah riset secara khusus menyoroti pola makan yang tepat demi kulit yang tampak lebih baik. Studi yang dipublikasikan di Journal of Investigative Dermatology menganalisa salah satu pola makan paling populer, yaitu diet ketogenik.</p>
              <p class="descarticle">Lemak sehat sangat penting untuk microbiome kulit yang sehat. Namun, studi ini menunjukkan, bahkan jenis lemak sehat sekalipun memiliki efek terhadap kulit. Dalam studi yang dilakukan terhadap hewan, para peneliti menganalisa berbagai variasi diet keto tinggi lemak -sebab tidak setiap orang mengikuti setiap rencana makan. Hasilnya, mereka menemukan lemak tertentu berdampak pada kondisi peradangan pada kulit. Diet ketogenik merupakan diet yang berat dalam trigliserida rantai menengah (MCT), seperti minyak kelapa, yang menyebabkan peradangan yang diinduksi psoriasis. Terutama, ketika lemak ini dikombinasikan dengan asam lemak omega-3</p>
              <p class="descarticle">Di sisi lain, para peneliti menemukan, diet keto seimbang dengan trigliserida rantai panjang (LCT), seperti minyak zaitun, minyak kedelai, ikan, kacang-kacangan, dan alpukat, tidak menyebabkan peradangan kulit. Singkatnya, jika kamu mengikuti diet keto dan rentan terhadap gejala-gejala seperti psoriasis, kamu mungkin perlu berhati-hati dengan minyak kelapa.</p>
              <p class="descarticle">Untuk diketahui, minyak kelapa merupakan salah satu bahan baku utama untuk para pelaku diet keto. Namun, MCT telah terbukti memiliki beberapa manfaat kesehatan yang tergolong signifikan, seperti meningkatkan energi, menurunkan kolesterol, mengelola epilepsi, dan lainnya. Jadi, bukan berarti kamu tidak boleh sama sekali mengonsumsi lemak ini. Bahkan, minyak kelapa juga telah terbukti dapat membantu gejala psoriasis ketika dioleskan ke kulit yang meradang. Meskipun penelitian lebih lanjut diperlukan untuk membuat korelasi yang pasti, studi ini hanya menekankan kecantikan kulit benar-benar diciptakan dari dalam dan dimulai dengan pola makan seimbang. Namun, apakah ini merupakan penyebab ruam keto? Penelitian ini bukan yang pertama untuk mengukur efek keto pada microbiome kulit. Para ilmuwan sebelumnya telah menciptakan kondisi yang disebut "ruam keto," setelah mempelajari tingkat peradangan kulit pada individu yang baru beralih ke pola makan keto.</p>
              <br>
            </div>

            <div class="col-sm-1">
             <br>
            </div>
          </div>

          <br> <br>

        </div>
        

</body>

article/templates/katering_article.html
{% extends 'base.html' %}

{% load static %}

{% block title %}Article | Cater.ing{% endblock title %}

{% block content %}

<body>


	<div class="container mt-5">
  <h1 style="font-weight: bold; margin: 0.8">FEATURED ARTICLE</h1>
  <hr class="new5" style="border: 2px solid black; ">


  <div id="myCarousel" class="carousel slide" data-ride="carousel">
    <!-- Indicators -->
    <ol class="carousel-indicators">
      <li data-target="#myCarousel" data-slide-to="0" class="active"></li>
      <li data-target="#myCarousel" data-slide-to="1" ></li>
      <li data-target="#myCarousel" data-slide-to="2" ></li>
    </ol>

    <!-- Wrapper for slides -->
    <div class="carousel-inner">
      <div class="item active">
        <a href="{% url 'article:artikelsatu' %}">
        <img src="{% static 'images/f.jpg' %}" class="crsl" style="height: 30%">
        <div class="carousel-caption">
          <p class="title">Diet Keto Bisa Picu Peradangan Kulit, Apa Sebabnya?</p>
        </div>
       </a>
      </div>

      <div class="item">
        <a href="{% url 'article:artikelsatu' %}">
        <img src="{% static 'images/f.jpg' %}" class="crsl">
        <div class="carousel-caption">
          <p class="title" >Diet Tidak Berhasil? Ini Adalah Penyebabnya!</p>
        </div>
      </a>
      </div>
    
      <div class="item">
        <img src="{% static 'images/f.jpg' %}" class="crsl">
        <div class="carousel-caption">
          <p class="title">Waspadai Camilan Berikut ini, Bisa Gagalkan Diet!</p>
        </div>
      </div>
  
    </div>

    <!-- Left and right controls -->
    <a class="left carousel-control" href="#myCarousel" data-slide="prev">
      <span class="glyphicon glyphicon-chevron-left"></span>
      <span class="sr-only">Previous</span>
    </a>
    <a class="right carousel-control" href="#myCarousel" data-slide="next">
      <span class="glyphicon glyphicon-chevron-right"></span>
      <span class="sr-only">Next</span>
    </a>
  </div>
  </div>
  
<br><br><br><br>

  <h2 style="font-weight: bold; margin: 0.8; text-align: center;">ALL ARTICLES</h2>
    <hr class="new5" style="border: 2px solid black; width: 79%; ">
    <br><br> 

    <div style="width: 79%; color: #000000;" class="card bg-info text-white">
    <div class="card-body">
      
    </div>
  </div>

	<div class="container">
  <div class="row">
    <div class="col-sm-1"></div>
    <div id = "at" class="col-sm-2"> <img class="featured" src="{% static 'images/f1.jpg' %}"> </div>
    <div id = "at" class="col-sm-7"> 
      <a href="{% url 'article:artikelsatu' %}" style="color: #000000; text-decoration:none">
    	   <p class="title">Diet Keto Bisa Picu Peradangan Kulit, Apa Sebabnya?</p>  
    	   <p>Kita semua tahu bahwa pola makan punya dampak yang berbeda-beda pada setiap individu. Pola makan juga sangat berdampak pada kulit. Banyak mengonsumsi makanan olahan dan tinggi gula, misalnya, terbukti merusak kulit. Sementara, banyak mengonsumsi sumber makanan nabati bisa membuat kulit tampak lebih berkilau dan halus.....</p> 
       </a>
    </div>
    <div class="col-sm-1"></div>
  </div>

  <br><br><br>
  <div class="row">
    <div class="col-sm-1"></div>
    <div id = "at" class="col-sm-2"> <img class="featured" src="{% static 'images/c.jpg' %}"> </div>
    <div id = "at" class="col-sm-7">
      <a href="{% url 'article:artikeldua' %}" style="color: #000000; text-decoration:none">
    	<p class="title">Cara Diet Turun Berat Badan yang Aman Tanpa Bahayakan Kesehatan</p>
    	<p>Sah-sah saja untuk mulai berdiet jika Anda mau punya berat badan ideal. Namun, Anda harus pintar-pintar membuat strateginya agar rencana diet sehat berjalan mulus tanpa hambatan. Alih-alih berat badan turun, angka di timbangan malah akan melonjak drastis jika salah strategi...</p>
    </a>
    </div>
    <div class="col-sm-1"></div>
  </div>
  <br><br><br>

  <div class="row">
    <div class="col-sm-1"></div>
    <div id = "at" class="col-sm-2"> <img class="featured" src="{% static 'images/f1.jpg' %}"> </div>
    <div id = "at" class="col-sm-7"> 
      <a href="{% url 'article:artikelsatu' %}" style="color: #000000; text-decoration:none">
         <p class="title">Diet Keto Bisa Picu Peradangan Kulit, Apa Sebabnya?</p>  
         <p>Kita semua tahu bahwa pola makan punya dampak yang berbeda-beda pada setiap individu. Pola makan juga sangat berdampak pada kulit. Banyak mengonsumsi makanan olahan dan tinggi gula, misalnya, terbukti merusak kulit. Sementara, banyak mengonsumsi sumber makanan nabati bisa membuat kulit tampak lebih berkilau dan halus.....</p> 
       </a>
    </div>
    <div class="col-sm-1"></div>
  </div>

  <br><br><br>
  <div class="row">
    <div class="col-sm-1"></div>
    <div id = "at" class="col-sm-2"> <img class="featured" src="{% static 'images/c.jpg' %}"> </div>
    <div id = "at" class="col-sm-7">
      <a href="{% url 'article:artikeldua' %}" style="color: #000000; text-decoration:none">
      <p class="title">Cara Diet Turun Berat Badan yang Aman Tanpa Bahayakan Kesehatan</p>
      <p>Sah-sah saja untuk mulai berdiet jika Anda mau punya berat badan ideal. Namun, Anda harus pintar-pintar membuat strateginya agar rencana diet sehat berjalan mulus tanpa hambatan. Alih-alih berat badan turun, angka di timbangan malah akan melonjak drastis jika salah strategi...</p>
    </a>
    </div>
    <div class="col-sm-1"></div>
  </div>
  <br><br><br>

</div>

  <h3 style="font-weight: bold; margin: 0.8; text-align: center;">SEARCH</h3>
    <hr class="new5" style="border: 1px solid black; width: 65%; ">

 <div class="container">
        <div class="row">
              <div class="col-sm-1">
              </div>
              <div class="col-sm-7">
                <form method="POST">
                  {% csrf_token %}
                <input class="form-control input-style center-content" type="text" name="word" placeholder="Search any keyword">
              </div>
              <div class="col-sm-3">
                <button type="submit" class="btn btn-primary">Search</button>
                </form>
              </div>
              <div class="col-sm-1"></div>
        </div>
</div>
<br><br>

<div class="container">
</div>

</body>
{% endblock %}

article/templates/search.html
{% extends 'base.html' %}
{% block content %}
    <div class="container mt-5 pt-5">
        <div class="row justify-content-center">
            <form class="text-center">
                <h1>Feel free to ask</h1>
                <input class="form-control input-style center-content" type="text" placeholder="Type something">
                <button type="submit" class="btn btn-primary">Search</button>
            </form>
        </div>
    </div>
{% endblock %}

homepage/templates/About Us.html
{% load static %}

<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <title>About Us | Cater.ing</title>
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <meta http-equiv="X-UA-Compatible" content="ie=edge">
    <link rel="stylesheet" href="{%static 'css/About-style.css' %}">

    <link href="https://fonts.googleapis.com/css?family=Playfair+Display|Poppins|Roboto&display=swap" rel="stylesheet">

    <link rel="stylesheet" href="https://maxcdn.bootstrapcdn.com/bootstrap/4.0.0/css/bootstrap.min.css" integrity="sha384-Gn5384xqQ1aoWXA+058RXPxPg6fy4IWvTNh0E263XmFcJlSAwiGgFAW/dAiS6JXm" crossorigin="anonymous">
        
    <script src="https://ajax.googleapis.com/ajax/libs/jquery/3.3.1/jquery.min.js"></script>
    <script src="https://cdnjs.cloudflare.com/ajax/libs/popper.js/1.14.7/umd/popper.min.js"></script>
    <script src="https://stackpath.bootstrapcdn.com/bootstrap/4.3.1/js/bootstrap.min.js"></script>
</head>
<body>
    <div id="wrapper">
        <div class="container-fluid m-auto">
                <div class="row pt-5 pl-5 pr-5">
                    <div class="col-lg-6 col-md-12 px-0 text-left content-about-us">
                        <h1>What are We?</h1>
                        <p>test test test test test test test test</p>
                        <p>test test test test test test test test</p>
                        <p></p>
                    </div>
                    <div class="col-lg-6 col-md-12 px-0 text-center content-our-team">
                        <img src="{% static 'images/undraw_healthy_options_sdo3.svg' %}" alt="Application" class="about-us-img" />
                    </div>
                </div>

                <div class="row pt-5 pl-5 pr-5">
                    <div class="col-lg-6 col-md-12 px-0 text-center content-our-team">
                        <img src="{% static 'images/Artboard 1.png' %}" alt="Application" class="about-us-img" />
                    </div>
                    <div class="col-lg-6 col-md-12 px-0 text-right content-about-us">
                        <h1>What are We Serving?</h1>
                        <p></p>
                    </div>
                </div>

                <div class="row pt-5 pl-5 pr-5">
                    <div class="col-lg-6 col-md-12 px-0 text-left content-about-us">
                        <h1>What are We?</h1>
                        <p></p>
                    </div>
                    <div class="col-lg-6 col-md-12 px-0 text-justify content-our-team">

                    </div>
                </div>

        </div>
    </div>
    <div class="d-flex flex-row-reverse bd-highlight justify-content-center">
        <div class="p-2 bd-highlight text-center"><a href="{% url 'homepage:homepage' %}">Back to Menu</a></div>
        <div class="p-2 bd-highlight text-center"><a href="{% url 'homepage:our-team' %}">Our Team</a></div>
        <div class="p-2 bd-highlight text-center">About Us</div>
        
    </div>
</body>
</html>

homepage/templates/Homepage.html
{% load static %}

<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <meta http-equiv="X-UA-Compatible" content="ie=edge">
    <title>Home | Cater-ing</title>

    <link rel="stylesheet" href="{% static 'css/Homepage-style.css' %}">

    <link href="https://fonts.googleapis.com/css?family=Playfair+Display|Poppins|Roboto&display=swap" rel="stylesheet">

    <link rel="stylesheet" href="https://maxcdn.bootstrapcdn.com/bootstrap/4.0.0/css/bootstrap.min.css" integrity="sha384-Gn5384xqQ1aoWXA+058RXPxPg6fy4IWvTNh0E263XmFcJlSAwiGgFAW/dAiS6JXm" crossorigin="anonymous">

</head>
<body>
    <div class="row">
        <div class="col-6"></div>
        <div class="col-6">
            <div class="container text-right homepage">
                <h1>Welcome!</h1>
                <p> We provide delicious healthy food <br>
                    and send it to your doorstep!</p>
                <a href="{% url 'homepage:qna' %}"><button type="submit" class="btn btn-info">Explore</button></a>
                <a href="{% url 'homepage:about-us' %}"><button type="submit" class="btn btn-info">About Us</button></a>
            </div>
        </div>
    </div>
</body>
</html>

homepage/templates/OurTeam-page.html
{% load static %}

<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <meta http-equiv="X-UA-Compatible" content="ie=edge">
    <title>Our Team | Cater.ing</title>

    <link href="https://fonts.googleapis.com/css?family=Playfair+Display|Poppins|Roboto&display=swap" rel="stylesheet">

    <link rel="stylesheet" href="https://maxcdn.bootstrapcdn.com/bootstrap/4.0.0/css/bootstrap.min.css" integrity="sha384-Gn5384xqQ1aoWXA+058RXPxPg6fy4IWvTNh0E263XmFcJlSAwiGgFAW/dAiS6JXm" crossorigin="anonymous">
    <script src="https://ajax.googleapis.com/ajax/libs/jquery/3.3.1/jquery.min.js"></script>
    <script src="https://cdnjs.cloudflare.com/ajax/libs/popper.js/1.14.7/umd/popper.min.js"></script>
    <script src="https://stackpath.bootstrapcdn.com/bootstrap/4.3.1/js/bootstrap.min.js"></script>
    
    <link rel="stylesheet" href="{%static 'css/OurTeam-style.css' %}">
</head>
<body>
    <div id="wrapper">
        <div class="container m-auto ">
            <div class="leftmost rightmost">
                <div class="row mx-2 h-100">
                    <div class="col-lg-6 col-md-12 px-2 my-auto text-justify content-our-team">
                        <h1 class="our-team-title">Our Team</h1>
                        <p class="our-team-subtitle"> We are from group 12, consisted of Alia, Ferdinand, Mikhael, and Jilham.
                            this is our first project in creating a website to fulfill the first group 
                            assignments in the course of web desing and programming. 

                        </p>
                    </div>
                    <div class="col-lg-6 col-md-12 px-2 text-center">
                        <img src="{% static 'images/undraw_team_spirit_hrr4.svg' %}" alt="Out Team Design" class="our-team-img">
                    </div>
                </div>
        
                <h3 class="text-center mt-5 our-team-text">~ Let's meet our fabulous creator ~</h3>
                <div id="carouselExampleControls" class="carousel slide carousel-background" data-ride="carousel">
                    <div class="carousel-inner">
                        <div class="carousel-item active">
                            <div class="carousel-content">
                                <img src="{% static 'images/Jilham Luthfi.jpg' %}" class="mx-auto d-block carousel-img" alt="Jilham Luthfi">
                                <div class="carousel-subtitle">
                                    <h5><strong>M. Jilham Luthfi</strong></h5>
                                    <p>Contribute in making of Q&A and About Us pages</p>
                                </div>
                            </div>
                        </div>
                        <div class="carousel-item">
                            <div class="carousel-content">
                                <img src="{% static 'images/Alia.png' %}" class="mx-auto d-block carousel-img" alt="Alia Junisar">
                                <div class="carousel-subtitle white-text">
                                    <h5><strong>Alia Junisar</strong></h5>
                                    <p>-</p>
                                </div>
                            </div>
                        </div>
                        <div class="carousel-item">
                            <div class="carousel-content">
                                <img src="{% static 'images/Jilham Luthfi.jpg' %}" class="mx-auto d-block carousel-img" alt="Jilham Luthfi">
                                <div class="carousel-subtitle white-text">
                                    <h5><strong>M. Jilham Luthfi</strong></h5>
                                    <p>-</p>
                                </div>
                            </div>
                        </div>
                        <div class="carousel-item">
                            <div class="carousel-content">
                                <img src="{% static 'images/Jilham Luthfi.jpg' %}" class="mx-auto d-block carousel-img" alt="Jilham Luthfi">
                                <div class="carousel-subtitle white-text">
                                    <h5><strong>M. Jilham Luthfi</strong></h5>
                                    <p>-</p>
                                </div>
                            </div>
                        </div>
                    </div>
                    <a class="carousel-control-prev" href="#carouselExampleControls" role="button" data-slide="prev">
                        <span class="carousel-control-prev-icon" aria-hidden="true"></span>
                        <span class="sr-only">Previous</span>
                    </a>
                    <a class="carousel-control-next" href="#carouselExampleControls" role="button" data-slide="next">
                        <span class="carousel-control-next-icon" aria-hidden="true"></span>
                        <span class="sr-only">Next</span>
                    </a>
                </div>
            </div>
        </div>
    </div>
    <div class="d-flex flex-row-reverse bd-highlight justify-content-center">
        <div class="p-2 bd-highlight text-center"><a href="{% url 'homepage:homepage' %}">Back to Menu</a></div>
        <div class="p-2 bd-highlight text-center">Our Team</div>
        <div class="p-2 bd-highlight text-center"><a href="{% url 'homepage:about-us' %}">About Us</a></div>
    </div>
    
    
</body>
</html>

homepage/templates/QnA-page.html
{% extends 'base.html' %}

{% block title %}QnA | Cater.ing{% endblock title %}

{% block content %}
    <div class="container mt-5 pt-5">
        <div class="row justify-content-center p-5">
            <form class="text-center" method="POST">
                {% csrf_token %}
                <h1>Feel free to ask</h1>
                <input class="form-control input-style center-content" type="text" name="keyword" placeholder="Type something">
                <button type="submit" class="btn btn-primary">Search</button>
            </form>
            
            <div class="mt-3 answer-box">
                {{answer.answer}}
            </div>
        </div>
    </div>
{% endblock %}

homepage/templates/base.html
{% load static %}

<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <meta http-equiv="X-UA-Compatible" content="ie=edge">
    <title>{% block title %}{% endblock title %}</title>

    <link href="https://fonts.googleapis.com/css?family=Lobster&display=swap" rel="stylesheet">
    <link href="https://fonts.googleapis.com/css?family=Montserrat&display=swap" rel="stylesheet">
    <link href="https://fonts.googleapis.com/css?family=Playfair+Display|Poppins|Roboto&display=swap" rel="stylesheet">

    <link rel="stylesheet" href="https://maxcdn.bootstrapcdn.com/bootstrap/4.0.0/css/bootstrap.min.css" integrity="sha384-Gn5384xqQ1aoWXA+058RXPxPg6fy4IWvTNh0E263XmFcJlSAwiGgFAW/dAiS6JXm" crossorigin="anonymous">
    <link rel="stylesheet" href="https://cdnjs.cloudflare.com/ajax/libs/font-awesome/4.7.0/css/font-awesome.min.css">

    <script src="https://ajax.googleapis.com/ajax/libs/jquery/3.3.1/jquery.min.js"></script>
    <script src="https://cdnjs.cloudflare.com/ajax/libs/popper.js/1.14.7/umd/popper.min.js"></script>
    <script src="https://stackpath.bootstrapcdn.com/bootstrap/4.3.1/js/bootstrap.min.js"></script>

    <link rel="stylesheet" href="{%static 'css/Navbar-style.css' %}"> 
    <link rel="stylesheet" href="{%static 'css/QnA-style.css' %}">
    <link rel="stylesheet" type="text/css" href="{% static 'css/article.css' %}">
</head>
<body>
    <nav class="navbar navbar-expand-lg navbar-dark bg-info fixed-top">
        <a class="navbar-brand header-title" href="#"><img src="{% static 'images/favicon.png' %}" width="50" height="50" alt="">
            <span class="header-title">Cater.ing</span>
        </a>
        <button class="navbar-toggler" type="button" data-toggle="collapse" data-target="#navbarSupportedContent" aria-controls="navbarSupportedContent" aria-expanded="false" aria-label="Toggle navigation">
            <span class="navbar-toggler-icon"></span>
        </button>
                
        <div class="collapse navbar-collapse" id="navbarSupportedContent">
            <ul class="navbar-nav ml-auto">
                <li class="nav-item active header-subtitle">
                    <a class="nav-link" href="{% url 'homepage:homepage'%}">Home <span class="sr-only">(current)</span></a>
                </li>
                <li class="nav-item active header-subtitle">
                    <a class="nav-link" href="#">Menu <span class="sr-only">(current)</span></a>
                </li>
                <li class="nav-item active header-subtitle">
                    <a class="nav-link" href="{% url 'homepage:qna'%}">Q&A<span class="sr-only">(current)</span></a>
                </li>
                <li class="nav-item active header-subtitle">
                    <a class="nav-link" href="{% url 'article:article' %}">Article <span class="sr-only">(current)</span></a>
                </li>
            </ul>
            <a href="{% url 'order:form_order'%}" class="btn btn-warning header-subtitle">Order Now</a> 
        </div>    
    </nav>

    {% block content %}
    {% endblock %}
</body>